apiVersion: v1
kind: Secret
metadata:
  name: foodndeliv-db-secret
type: Opaque
stringData:
  password: "rprPgyUAWOC5VitEKLF1YMGzl2VxySpa4CgN75HlL4iy9qYLoBJkmdlzUEZB73Yg"
  username: "foodndeliv_user"